### ISSUE TITLE
发送信息的时候报错

### ISSUE THREAD

**Issue by itmanmax** [wcwq98/ChatGPT_Plugin_QQMusic#1]
说文件路径不正确

**Comment by itmanmax** [comment]
![image](https://github.com/user-attachments/assets/a8d7e388-53c8-4299-a070-37bd7103f116)

**Comment by wcwq98** [comment]
你看看是不是文件目录的问题
![image](https://github.com/user-attachments/assets/ac80b43f-8acf-4935-b276-0ed848027986)

**Comment by wcwq98** [comment]
有问题在群里@我（@小白求教）

**Comment by Yumikolab** [comment]
> 有问题在群里@我（@小白求教）

哪个群？

**Comment by wcwq98** [comment]
我q1311265677
